// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PNedov.IsiMarkets.EtlPipeline.Repositories;

#nullable disable

namespace PNedov.IsiMarkets.EtlPipeline.Migrations
{
    [DbContext(typeof(TransactionsDbContext))]
    partial class TransactionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PNedov.IsiMarkets.EtlPipeline.Models.CustomerTransactions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customers_id")
                        .HasColumnOrder(9);

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(19, 4)")
                        .HasColumnName("discount")
                        .HasColumnOrder(5);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("location")
                        .HasColumnOrder(7);

                    b.Property<int>("PaymentMethodsId")
                        .HasColumnType("int")
                        .HasColumnName("payment_methods_id")
                        .HasColumnOrder(11);

                    b.Property<int>("ProductsId")
                        .HasColumnType("int")
                        .HasColumnName("products_id")
                        .HasColumnOrder(10);

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(19, 4)")
                        .HasColumnName("quantity")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp")
                        .HasColumnOrder(8);

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(19, 4)")
                        .HasColumnName("total_price")
                        .HasColumnOrder(6);

                    b.Property<int>("TransctionStatusesId")
                        .HasColumnType("int")
                        .HasColumnName("transction_statuses_id")
                        .HasColumnOrder(12);

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("unique_id")
                        .HasColumnOrder(2);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(19, 4)")
                        .HasColumnName("unitprice")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentMethodsId");

                    b.HasIndex("ProductsId");

                    b.HasIndex("TransctionStatusesId");

                    b.ToTable("customers_transactions");
                });

            modelBuilder.Entity("PNedov.IsiMarkets.EtlPipeline.Models.Customers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("cust_email")
                        .HasColumnOrder(5);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("fname")
                        .HasColumnOrder(3);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("lname")
                        .HasColumnOrder(4);

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("unique_id")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "LastName", "CustomerEmail");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("PNedov.IsiMarkets.EtlPipeline.Models.PaymentMethodTypes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("iname")
                        .HasColumnOrder(2);

                    b.HasKey("id");

                    b.ToTable("payment_methods");
                });

            modelBuilder.Entity("PNedov.IsiMarkets.EtlPipeline.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("idesc")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("iname")
                        .HasColumnOrder(3);

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("unique_id")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("products");
                });

            modelBuilder.Entity("PNedov.IsiMarkets.EtlPipeline.Models.SystemConfigurations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("unique_id")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("system_configurations");
                });

            modelBuilder.Entity("PNedov.IsiMarkets.EtlPipeline.Models.TransctionStatuses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("iname")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("transction_statuses");
                });

            modelBuilder.Entity("PNedov.IsiMarkets.EtlPipeline.Models.CustomerTransactions", b =>
                {
                    b.HasOne("PNedov.IsiMarkets.EtlPipeline.Models.Customers", "Customers")
                        .WithMany("CustomerTransctions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PNedov.IsiMarkets.EtlPipeline.Models.PaymentMethodTypes", "PaymentMethods")
                        .WithMany("CustomerTransctions")
                        .HasForeignKey("PaymentMethodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PNedov.IsiMarkets.EtlPipeline.Models.Products", "Products")
                        .WithMany("CustomerTransctions")
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PNedov.IsiMarkets.EtlPipeline.Models.TransctionStatuses", "Statuses")
                        .WithMany("CustomerTransctions")
                        .HasForeignKey("TransctionStatusesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customers");

                    b.Navigation("PaymentMethods");

                    b.Navigation("Products");

                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("PNedov.IsiMarkets.EtlPipeline.Models.Customers", b =>
                {
                    b.Navigation("CustomerTransctions");
                });

            modelBuilder.Entity("PNedov.IsiMarkets.EtlPipeline.Models.PaymentMethodTypes", b =>
                {
                    b.Navigation("CustomerTransctions");
                });

            modelBuilder.Entity("PNedov.IsiMarkets.EtlPipeline.Models.Products", b =>
                {
                    b.Navigation("CustomerTransctions");
                });

            modelBuilder.Entity("PNedov.IsiMarkets.EtlPipeline.Models.TransctionStatuses", b =>
                {
                    b.Navigation("CustomerTransctions");
                });
#pragma warning restore 612, 618
        }
    }
}
